version: "3"

services:
    production-service:
        build: .
        platform: linux/x86_64
        networks:
            - anser_project_network
        ports:
            - 8081:8080
        working_dir: /app
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_MEMORY_LIMIT=2048M
            - PHP_MAX_EXECUTION_TIME=300
            - PHP_POST_MAX_SIZE=2048M
            - PHP_UPLOAD_MAX_FILESIZE=2048M
            - SERVICE_ID=production-2
        volumes:
            - './app:/app'
            - './logs/supervisor:/var/log/supervisor'
        command: >
            bash -c "chmod +x /app/start_service.sh && /app/start_service.sh"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
    production_DB:
        image: postgres:11.12
        networks:
            - anser_project_network
        environment:
            POSTGRES_DB: production
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - ./production-db-data:/var/lib/postgresql/data/
        ports:
            - "8310:5432"
        command:
            [
                "postgres",
                "-c",
                "logging_collector=on",
                "-c",
                "log_destination=stderr",
                "-c",
                "max_connections=50000"
            ]
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"       # AMQP 連接埠
            - "15672:15672"     # 管理介面
        networks:
            - anser_project_network

    # production_test_DB:
    #     image: postgres:11.12
    #     networks:
    #         - anser_project_network
    #     environment:
    #         POSTGRES_DB: production
    #         POSTGRES_USER: root
    #         POSTGRES_PASSWORD: root
    #     volumes:
    #         - ./production-test-db-data:/var/lib/postgresql/data/
    #     ports:
    #         - "8311:5432"
    #     command:
    #         [
    #             "postgres",
    #             "-c",
    #             "logging_collector=on",
    #             "-c",
    #             "log_destination=stderr",
    #             "-c",
    #             "max_connections=50000"
    #         ]
networks:
    anser_project_network:
        external: true

