[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=5MB
logfile_backups=3
loglevel=info
pidfile=/tmp/supervisord.pid
childlogdir=/var/log/supervisor

[program:php-service]
command=php spark burner:start
directory=/app
autostart=true
autorestart=true
startsecs=3
stderr_logfile=/var/log/supervisor/php-service.err.log
stdout_logfile=/var/log/supervisor/php-service.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB

[program:report_metrics]
command=php /app/report_metrics.php
directory=/app
autostart=true
autorestart=true
startsecs=2
stderr_logfile=/var/log/supervisor/metrics.err.log
stdout_logfile=/var/log/supervisor/metrics.log
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
